ALTER TABLE IF EXISTS users
ALTER COLUMN created_at DROP DEFAULT,
ALTER COLUMN updated_at DROP DEFAULT;

ALTER TABLE IF EXISTS programs
ALTER COLUMN created_at DROP DEFAULT,
ALTER COLUMN updated_at DROP DEFAULT;

ALTER TABLE IF EXISTS email_verification_otps
ALTER COLUMN created_at DROP DEFAULT;
